const CONFIG = {
    introTitle: 'Chị iu ơi :<<',
    introDesc: 'Gọii chị làa mặt trời vĩ đại còn em là trái đất, vì em sẽ vì chị mà phát cuồng đến nỗi quay quanh chị <33',
    btnIntro: 'ngạiii quáaa hihii',
    title: 'Awwwwww em đã iuuu chị từ cái nhìn đầu tiênnnn nèee 😙',
    desc: 'say chị còn say hơn cả say rượuuu ',
    btnYes: 'Mong chị vẫn thít em mãi nhoaaa:33 <33',
    btnNo: 'Có cl nè bé =)))',
    question:'Dòng đời đưa đẩyy sao chị lại đến bên emm:33',
    btnReply: 'Reply cho em nhéeee',
    reply: 'Yêu em hoặc bị hunnnnn aaaaaaa:33 <33',
    mess: 'Thương emm nhiềuuuu:33 , Mãi juu Bé của anhhhh:333 <33',
    messDesc: 'Mình gặp rồi d1t nhau em nhé =))) <3',
    btnAccept: 'dạaaaa anhhiuuu:33 <3',
    
